/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MsAmbulanceWlList {
    }
}
declare global {
    interface HTMLMsAmbulanceWlListElement extends Components.MsAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMsAmbulanceWlListElement: {
        prototype: HTMLMsAmbulanceWlListElement;
        new (): HTMLMsAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "ms-ambulance-wl-list": HTMLMsAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MsAmbulanceWlList {
    }
    interface IntrinsicElements {
        "ms-ambulance-wl-list": MsAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ms-ambulance-wl-list": LocalJSX.MsAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMsAmbulanceWlListElement>;
        }
    }
}
